### ISSUE TITLE
How to use with named formatting?

### ISSUE THREAD

**Issue by kaangokdemir** [phrase/vue-i18n-phrase-in-context-editor#22]
Hello and thanks for having this package. I wonder how to use the context editor with [Named Formatting](https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting)

I checked `examples/basic` but couldn't find any example for named formatting usage. I'd tried to change title as

```html
<h2>{{ $t("title", { number: 3 }) }}</h2>
```

and the related translation to

```html
<i18n>
{
  "en": {
    "title": "Dummy title {number}",
    "headline": "",
    "intro": "",
    "text": ""
  }
}
</i18n>
```

however it did not worked for some reason. Instead I received this screen below with `Dummy title {number}` as hardcoded:

<img width="1440" alt="Screenshot 2021-03-28 at 21 01 59" src="https://user-images.githubusercontent.com/51219535/112764479-04871880-9009-11eb-81a4-bdfbbd2efdea.png">

I also added my translation to `Translation Center`

**Comment by theSoenke** [comment]
Hey @kaangokdemir, the InContext-Editor is currently only displaying the translation from Phrase. Placeholder values are being currently being ignored. It would definitely be great to actually show the placeholder values in the translation but we have no looked further into this yet.
