### ISSUE TITLE
lack of type definitions in node_modules

### ISSUE THREAD

**Issue by SunnyCrypto** [phrase/vue-i18n-phrase-in-context-editor#4]
Once installed this dependency in node_modules, I can't find the type definitions, there is no src directory.

![image](https://user-images.githubusercontent.com/59635374/84626589-f05da900-af17-11ea-9f4f-ee635128f6e2.png)

![image](https://user-images.githubusercontent.com/59635374/84626640-079c9680-af18-11ea-827d-7fda78c7bdd3.png)

Please include the type definitions when publish it to npm.

**Comment by FRSgit** [comment]
Hey @SunnyCrypto, thanks for bringing this up!

Before anything, I have one question - why are you importing `index.ts` file explicitly? The main import file is `./dist/vue-i18n-phrase-in-context-editor.umd.js` as configured [here](
https://github.com/phrase/vue-i18n-phrase-in-context-editor/blob/master/package.json#L8-L9).

If you import our library as described in [docs](https://phrase.github.io/vue-i18n-phrase-in-context-editor/guide/getting-started/#usage) then the typings should work right away (they're shipped in dist directory):
```ts
import VueI18nPhraseInContextEditor from 'vue-i18n-phrase-in-context-editor';
```

We also provide the **CommonJS** bundle in our package (`vue-i18n-phrase-in-context-editor.common.js`), but for this you would need to directly import the declaration file from `dist` directory (it's under `dist/index.d.ts`).

**Comment by SunnyCrypto** [comment]
@FRSgit 
Our project is vue + typescript.
I didn't import the `index.d.ts` manually.
I guess you have defined the types in package.json, then ts auto import the type definition file `index.d.ts`.

```json
  "types": "./dist/index.d.ts",
```

**Comment by FRSgit** [comment]
@SunnyCrypto 
Yes, the wrong capture has mislead me a bit 😄 You were right! The type definition files were missing from published `dist` directory.

I've fixed the release configuration and it seems to be including typings correctly now. Can you please test it as well and give me a feedback here if the issue is gone?

**Comment by SunnyCrypto** [comment]
@FRSgit it works after I installed the `1.0.2`, thanks!

**Comment by FRSgit** [comment]
@SunnyCrypto Sure, big thank you for finding this and providing useful feedback! 😉
