### ISSUE TITLE
Unable to sign out properly

### ISSUE THREAD

**Issue by henrikbernstrom** [phrase/vue-i18n-phrase-in-context-editor#6]
Using vue-i18n-phrase-in-context-editor@1.0.2 and when having signed in for the first time, using this vue plugin, it seems impossible to sign out properly. Even when specifying autoLogin: false. This is the setup options I'm using:

```
  const phrase = new VueI18nPhraseInContextEditor(i18n, {
    phraseEnabled: false,
    projectId: phraseProjectId,
    autoLowercase: false,
    autoLogin: {
      perform: false,
    },
  });
```
I'm toggling `phraseEnabled` via menu, programatically.

**Comment by FRSgit** [comment]
What do you mean by "not able to sign out properly"? Doesn't the login window pop-up after clicking "Logout" button?
Can you please share the reproduction scenario - what should I do to reproduce this error and what's exactly the error?

**Comment by FRSgit** [comment]
Sadly, I cannot reproduce this issue with the information you've provided. For me with the same config there is still a possibility to be signed out by clicking "sign out" button in the menu located in the bottom-right corner of the screen.
After doing the logout you need to login again to continue, which is an expected behaviour.

Please feel free to reopen this issue whenever you bump into this bug again!

**Comment by henrikbernstrom** [comment]
Sorry for not following up on this one. Vacation and stuff. But what I mean is, it sure looks like you're signed out, but once refreshing the page, you're all good to go again (signed in). Are you experiencing the same thing?

**Comment by FRSgit** [comment]
@henrikbernstrom Actually no, I tried exactly the same scenario and well, after refresh I'm just logged out.
Hm, you can give me the info about your OS & browser (name & version).

Would it be possible for you to prepare an environment when you can reproduce the problem? Like on some kind of codepen/jsbin/jsfiddle or sth? I cannot reproduce it with the demo app, so it would be perfect to be sure that we have exactly the same code 🔎
